[package]
name = "tlennis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "*"
rand = "*"
once_cell = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"